// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA82qLqxScpmEjiKx5uYkhEbLs842s_M1Q',
    appId: '1:168912656364:web:94deb43b8521ba257c52c9',
    messagingSenderId: '168912656364',
    projectId: 'chat-app-c2fc9',
    authDomain: 'chat-app-c2fc9.firebaseapp.com',
    storageBucket: 'chat-app-c2fc9.appspot.com',
    measurementId: 'G-LE5EVG5ZV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1M90K3HTy0cSGKzP77YnrhXd7fxpUy9k',
    appId: '1:168912656364:android:f3c51e1a3ffb8fb07c52c9',
    messagingSenderId: '168912656364',
    projectId: 'chat-app-c2fc9',
    storageBucket: 'chat-app-c2fc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvfFIfwKBNxlI0AVC_NazX9Qa75KYFYzo',
    appId: '1:168912656364:ios:9fb5251106f1d6fd7c52c9',
    messagingSenderId: '168912656364',
    projectId: 'chat-app-c2fc9',
    storageBucket: 'chat-app-c2fc9.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvfFIfwKBNxlI0AVC_NazX9Qa75KYFYzo',
    appId: '1:168912656364:ios:9fb5251106f1d6fd7c52c9',
    messagingSenderId: '168912656364',
    projectId: 'chat-app-c2fc9',
    storageBucket: 'chat-app-c2fc9.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA82qLqxScpmEjiKx5uYkhEbLs842s_M1Q',
    appId: '1:168912656364:web:ea7972ee6194c2227c52c9',
    messagingSenderId: '168912656364',
    projectId: 'chat-app-c2fc9',
    authDomain: 'chat-app-c2fc9.firebaseapp.com',
    storageBucket: 'chat-app-c2fc9.appspot.com',
    measurementId: 'G-FHKK0D33B9',
  );
}
